### ISSUE TITLE
New Icon Set

### ISSUE THREAD

**Issue by ghost** [material-extensions/vscode-material-product-icons#4]
I am a big fan of the old VSCode icons, I really like them a lot. So, my request to you is that can you create another icon theme for those? When I got the Material ones, I saw the VSCode Icons 1.0 there, but I do not know how to get those icons on my computer. 
Hope you make a new theme for those.
Thanks in advance

**Comment by PKief** [comment]
Hi, I'm not sure if I really get your point. You like the VS Code Icons 1.0 and you can use them right? If you select the VS Code Icons 1.0 instead of the Material Product Icons then they should be visible. The feature of product icons is already available in the Insiders version of VS Code and will be soon available in the official stable v1.53, which will be released in the next days, probably tomorrow.

**Comment by ghost** [comment]
I am not able to see them when I select the Product Icon Option, that is why I asked. I got the insiders version a few days back, so I think that is the reason

**Comment by ghost** [comment]
Also, the VS Code Icons 1.0 are the old icons, right? Not the default, but the ones before those

**Comment by PKief** [comment]
Yes, VS Code Icons are the old icons. In the official release of today (v1.53) they are not available. At least I cannot select nor install the icons via the Marketplace. Not sure why VS Code removed it from the stable release version. I also liked them.

I think I've found the icons that you are looking for. They are part of the extension samples repository. Feel free to check them out:
https://github.com/microsoft/vscode-extension-samples/tree/master/product-icon-theme-sample

**Comment by ghost** [comment]
Thanks alot!
